services:
  # --- API GATEWAY (Entry Point) ---
  api-gateway:
    container_name: api-gateway
    image: 10xdevian134/api-gateway:prod
    build:
      context: .
      dockerfile: docker/api-gateway/Dockerfile
    restart: always
    ports:
      - "80:8080" # Maps public traffic to Gateway
    env_file: .env.prod
    networks:
      - fish-studio-net

  # --- AUTH SERVICE ---
  auth-service:
    container_name: auth-service
    image: 10xdevian134/auth-service:prod
    build:
      context: .
      dockerfile: docker/auth-service/Dockerfile
    restart: always
    env_file: .env.prod
    expose:
      - "6001"
    networks:
      fish-studio-net:
        aliases:
          - auth-service

  # --- PRODUCT SERVICE ---
  product-service:
    container_name: product-service
    image: 10xdevian134/product-service:prod
    build:
      context: .
      dockerfile: docker/product-service/Dockerfile
    restart: always
    env_file: .env.prod
    expose:
      - "6003"
    networks:
      fish-studio-net:
        aliases:
          - product-service

  # --- PRODUCT SERVICE ---
  order-service:
    container_name: order-service
    image: 10xdevian134/order-service:prod
    build:
      context: .
      dockerfile: docker/order-service/Dockerfile
    restart: always
    env_file: .env.prod
    expose:
      - "6003"
    networks:
      fish-studio-net:
        aliases:
          - product-service

  # --- RABBITMQ BROKER ---
  rabbitmq-service:
    container_name: rabbitmq-service
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mysecretpassword
    ports:
      - "15672:15672"
    expose:
      - "5672"
    networks:
      fish-studio-net:
        aliases:
          - rabbitmq-service

  # --- MEILISEARCH ---
  meilisearch:
    container_name: meilisearch
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      - MEILI_MASTER_KEY=masterKey123
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    networks:
      fish-studio-net:
        aliases:
          - meilisearch

  # --- RABBITMQ WORKER ---
  worker-service:
    container_name: worker-worker
    image: 10xdevian134/worker-service:prod
    build:
      context: .
      dockerfile: docker/worker-service/Dockerfile
    restart: always
    env_file: .env.prod
    depends_on:
      - rabbitmq-service
    networks:
      - fish-studio-net

networks:
  fish-studio-net:
    driver: bridge
