services:
  api-gateway:
    container_name: api-gateway
    image: 10xdevian134/api-gateway:prod
    build:
      context: .
      dockerfile: docker/api-gateway/Dockerfile
    restart: always
    ports:
      - "80:8080"
    env_file: .env.prod
    depends_on:
      - auth-service
      - product-service
      - order-service
      - notification-service
    environment:
      AUTH_SERVICE_URL: http://auth-service:6001
      PRODUCT_SERVICE_URL: http://product-service:6003
      ORDER_SERVICE_URL: http://order-service:6004
      NOTIFICATION_SERVICE_URL: http://notification-service:6005
    networks:
      - fish-studio-net

  auth-service:
    container_name: auth-service
    image: 10xdevian134/auth-service:prod
    build:
      context: .
      dockerfile: docker/auth-service/Dockerfile
    restart: always
    env_file: .env.prod
    depends_on:
      - rabbitmq-service
    expose:
      - "6001"
    networks:
      fish-studio-net:
        aliases:
          - auth-service

  product-service:
    container_name: product-service
    image: 10xdevian134/product-service:prod
    build:
      context: .
      dockerfile: docker/product-service/Dockerfile
    restart: always
    env_file: .env.prod
    depends_on:
      - meilisearch
    expose:
      - "6003"
    networks:
      fish-studio-net:
        aliases:
          - product-service

  order-service:
    container_name: order-service
    image: 10xdevian134/order-service:prod
    build:
      context: .
      dockerfile: docker/order-service/Dockerfile
    restart: always
    env_file: .env.prod
    depends_on:
      - rabbitmq-service
    expose:
      - "6004"
    networks:
      fish-studio-net:
        aliases:
          - order-service

  notification-service:
    container_name: notification-service
    image: 10xdevian134/notification-service:prod
    build:
      context: .
      dockerfile: docker/notification-service/Dockerfile
    restart: always
    env_file: .env.prod
    depends_on:
      - rabbitmq-service
    expose:
      - "6005"
    networks:
      fish-studio-net:
        aliases:
          - notification-service

  rabbitmq-service:
    container_name: rabbitmq-service_prod
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mysecretpassword
    ports:
      - "15672:15672"
      - "5672:5672"
    networks:
      fish-studio-net:
        aliases:
          - rabbitmq-service

  meilisearch:
    container_name: meilisearch_prod
    image: getmeili/meilisearch:latest
    restart: always
    environment:
      - MEILI_MASTER_KEY=masterKey123
    ports:
      - "7700:7700"
    volumes:
      - ./meili_data:/meili_data
    networks:
      fish-studio-net:
        aliases:
          - meilisearch

  worker-service:
    container_name: worker-service
    image: 10xdevian134/worker-service:prod
    build:
      context: .
      dockerfile: docker/worker-service/Dockerfile
    restart: always
    env_file: .env.prod
    depends_on:
      - rabbitmq-service
    networks:
      fish-studio-net:
        aliases:
          - worker-service

networks:
  fish-studio-net:
    driver: bridge
