services:
  # --- API GATEWAY (Entry Point) ---
  api-gateway:
    container_name: api-gateway
    image: 10xdevian134/api-gateway:prod
    restart: always
    ports:
      - "80:8080" # Maps public traffic to Gateway
    env_file: .env.prod
    networks:
      - fish-studio-net

  # --- AUTH SERVICE ---
  auth-service:
    container_name: auth-service
    image: 10xdevian134/auth-service:prod
    restart: always
    env_file: .env.prod
    expose:
      - "6001"
    networks:
      fish-studio-net:
        aliases:
          - auth-service

  # --- PRODUCT SERVICE ---
  product-service:
    container_name: product-service
    image: 10xdevian134/product-service:prod
    restart: always
    env_file: .env.prod
    expose:
      - "6002"
    networks:
      fish-studio-net:
        aliases:
          - product-service

  # --- RABBITMQ BROKER ---
  rabbitmq-service:
    container_name: rabbitmq-service
    image: rabbitmq:3-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=mysecretpassword
    ports:
      - "15672:15672"
    expose:
      - "5672"
    networks:
      fish-studio-net:
        aliases:
          - rabbitmq-service

  # --- RABBITMQ WORKER ---
  rabbitmq-worker:
    container_name: rabbitmq-worker
    image: 10xdevian134/rabbitmq-service:prod
    restart: always
    env_file: .env.prod
    depends_on:
      - rabbitmq-service
    networks:
      - fish-studio-net

networks:
  fish-studio-net:
    driver: bridge